name: Compile LaTeX to PDF and Push to GitHub

on:
  push:
    branches:
      - main # o il nome del tuo branch principale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive
        # Aggiungi altri comandi se necessario per installare pacchetti LaTeX aggiuntivi

      - name: Compile LaTeX to PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error cv/main.tex
        # Sostituisci 'your_file.tex' con il nome del tuo file LaTeX

      - name: Add PDF to Git Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv cv/main.pdf output.pdf
          git add cv/output.pdf
          git commit -m "Aggiorna il file PDF"
          git push